name: CI

# N.B.: release.yml should be updated to match as necessary
permissions: {}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    # Pin Ubuntu to 20.04 to avoid failures with /sys/fs/cgroup not being compatible
    # with integration tests running systemd in a container on an older Ubuntu version.
    runs-on: ubuntu-20.04

    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
      id: go

    - name: Set up protoc
      uses: pganalyze/setup-protoc@v1.1.2
      with:
        version: 3.14.0
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Check out code
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Runs tests
      run: |
        make build OUTFILE=pganalyze-collector-linux-amd64
        DOCKER_BUILDKIT=1 make integration_test
        #make test
        shellcheck contrib/install.sh

    - name: Lint
      run: |
        test $(go fmt ./... | wc -l) -eq 0
